<?php
/**
 * Homepage "upcoming departures": one tab per season.
 *
 * Ported from `section.section--dark#seasons` of the reference layout. The
 * `.rail-dots` indicators are generated by assets/js/main.js. The whole section
 * is skipped without the companion plugin, which owns the season taxonomy.
 *
 * @package Elita_Tour
 */

$elita_tour_seasons = elita_tour_get_seasons();

if ( empty( $elita_tour_seasons ) ) {
	return;
}

$elita_tour_panels = array();

foreach ( $elita_tour_seasons as $elita_tour_season ) {
	$elita_tour_query = elita_tour_get_season_tours( $elita_tour_season->slug );

	if ( ! $elita_tour_query->have_posts() ) {
		continue;
	}

	$elita_tour_panels[] = array(
		'term'  => $elita_tour_season,
		'query' => $elita_tour_query,
	);
}

if ( empty( $elita_tour_panels ) ) {
	return;
}

$elita_tour_active = elita_tour_current_season_slug();
$elita_tour_slugs  = array();

foreach ( $elita_tour_panels as $elita_tour_panel ) {
	$elita_tour_slugs[] = $elita_tour_panel['term']->slug;
}

if ( ! in_array( $elita_tour_active, $elita_tour_slugs, true ) ) {
	$elita_tour_active = $elita_tour_slugs[0];
}
?>
<section class="section section--dark" id="seasons">
	<div class="container">
		<div class="section__head">
			<div>
				<span class="eyebrow"><?php esc_html_e( 'Holidays by the calendar', 'elita-tour' ); ?></span>
				<h2><?php esc_html_e( 'Upcoming departures', 'elita-tour' ); ?></h2>
			</div>

			<div class="tabs chips chips--scroll" role="tablist" aria-label="<?php esc_attr_e( 'Season', 'elita-tour' ); ?>">
				<?php
				foreach ( $elita_tour_panels as $elita_tour_panel ) :
					$elita_tour_slug      = $elita_tour_panel['term']->slug;
					$elita_tour_is_active = ( $elita_tour_slug === $elita_tour_active );
					?>
					<button
						class="chip<?php echo $elita_tour_is_active ? ' is-active' : ''; ?>"
						type="button"
						role="tab"
						id="tab-<?php echo esc_attr( $elita_tour_slug ); ?>"
						aria-controls="panel-<?php echo esc_attr( $elita_tour_slug ); ?>"
						aria-selected="<?php echo $elita_tour_is_active ? 'true' : 'false'; ?>"
					><?php echo esc_html( $elita_tour_panel['term']->name ); ?></button>
				<?php endforeach; ?>
			</div>
		</div>

		<?php
		foreach ( $elita_tour_panels as $elita_tour_panel ) :
			$elita_tour_slug      = $elita_tour_panel['term']->slug;
			$elita_tour_is_active = ( $elita_tour_slug === $elita_tour_active );
			?>
			<div class="rail" role="tabpanel" tabindex="0" id="panel-<?php echo esc_attr( $elita_tour_slug ); ?>" aria-labelledby="tab-<?php echo esc_attr( $elita_tour_slug ); ?>" <?php echo $elita_tour_is_active ? '' : 'hidden'; ?>>
				<?php
				foreach ( $elita_tour_panel['query']->posts as $elita_tour_post ) {
					get_template_part(
						'template-parts/tour/poster',
						null,
						array( 'post' => $elita_tour_post )
					);
				}
				?>
			</div>
		<?php endforeach; ?>
	</div>
</section><!-- #seasons -->
