<?php
/**
 * Homepage "upcoming departures": one tab per season.
 *
 * Ported from `section.section--dark#seasons` of the reference layout. The
 * `.rail-dots` indicators are generated by assets/js/main.js. The whole section
 * is skipped without the companion plugin, which owns the season taxonomy.
 *
 * @package WHA_Tour_Poster
 */

$wha_tour_poster_seasons = wha_tour_poster_get_seasons();

if ( empty( $wha_tour_poster_seasons ) ) {
	return;
}

$wha_tour_poster_panels = array();

foreach ( $wha_tour_poster_seasons as $wha_tour_poster_season ) {
	$wha_tour_poster_query = wha_tour_poster_get_season_tours( $wha_tour_poster_season->slug );

	if ( ! $wha_tour_poster_query->have_posts() ) {
		continue;
	}

	$wha_tour_poster_panels[] = array(
		'term'  => $wha_tour_poster_season,
		'query' => $wha_tour_poster_query,
	);
}

if ( empty( $wha_tour_poster_panels ) ) {
	return;
}

$wha_tour_poster_active = wha_tour_poster_current_season_slug();
$wha_tour_poster_slugs  = array();

foreach ( $wha_tour_poster_panels as $wha_tour_poster_panel ) {
	$wha_tour_poster_slugs[] = $wha_tour_poster_panel['term']->slug;
}

if ( ! in_array( $wha_tour_poster_active, $wha_tour_poster_slugs, true ) ) {
	$wha_tour_poster_active = $wha_tour_poster_slugs[0];
}
?>
<section class="section section--dark" id="seasons">
	<div class="container">
		<div class="section__head">
			<div>
				<span class="eyebrow"><?php esc_html_e( 'Holidays by the calendar', 'wha-tour-poster' ); ?></span>
				<h2><?php esc_html_e( 'Upcoming departures', 'wha-tour-poster' ); ?></h2>
			</div>

			<div class="tabs chips chips--scroll" role="tablist" aria-label="<?php esc_attr_e( 'Season', 'wha-tour-poster' ); ?>">
				<?php
				foreach ( $wha_tour_poster_panels as $wha_tour_poster_panel ) :
					$wha_tour_poster_slug      = $wha_tour_poster_panel['term']->slug;
					$wha_tour_poster_is_active = ( $wha_tour_poster_slug === $wha_tour_poster_active );
					?>
					<button
						class="chip<?php echo $wha_tour_poster_is_active ? ' is-active' : ''; ?>"
						type="button"
						role="tab"
						id="tab-<?php echo esc_attr( $wha_tour_poster_slug ); ?>"
						aria-controls="panel-<?php echo esc_attr( $wha_tour_poster_slug ); ?>"
						aria-selected="<?php echo $wha_tour_poster_is_active ? 'true' : 'false'; ?>"
					><?php echo esc_html( $wha_tour_poster_panel['term']->name ); ?></button>
				<?php endforeach; ?>
			</div>
		</div>

		<?php
		foreach ( $wha_tour_poster_panels as $wha_tour_poster_panel ) :
			$wha_tour_poster_slug      = $wha_tour_poster_panel['term']->slug;
			$wha_tour_poster_is_active = ( $wha_tour_poster_slug === $wha_tour_poster_active );
			?>
			<div class="rail" role="tabpanel" tabindex="0" id="panel-<?php echo esc_attr( $wha_tour_poster_slug ); ?>" aria-labelledby="tab-<?php echo esc_attr( $wha_tour_poster_slug ); ?>" <?php echo $wha_tour_poster_is_active ? '' : 'hidden'; ?>>
				<?php
				foreach ( $wha_tour_poster_panel['query']->posts as $wha_tour_poster_post ) {
					get_template_part(
						'template-parts/tour/poster',
						null,
						array( 'post' => $wha_tour_poster_post )
					);
				}
				?>
			</div>
		<?php endforeach; ?>
	</div>
</section><!-- #seasons -->
